### ISSUE TITLE
Attributes Style Convention

### ISSUE THREAD

**Issue by IdanCo** [IdanCo/ng1bs4#46]
@langdonx - I see you avoided adding prefixes the components' attributes (bindings).

so instead of
```html
<my-component my-component-attribute="1" my-component-other-attribute="2"></my-component>
```

you created
```html
<my-component attribute="1" other-attribue="2"></my-component>
```

It's evident that your approach is shorter and more readable. But I'm in favor of the verbose approach, for two reasons -
1. A component might have another directive on the same element (such as tooltip), which could lead to overlapping attributes
2. A component might rely on native angular directives (ng-model, ng-click) which i would like clearly separate.

Thoughts? Am i being to OCD here?

**Comment by langdonx** [comment]
I noticed this as well and was going to ask you which you preferred.  I think `title` on `ngbs-tabs` was the only exception I found (the docs still refer to `menu` as `ngbs-dropdown`, but the attributes are correct).

I don't like the verbosity, but I think because of the risk of attribute directives (and native HTML attributes like disabled), it makes perfect sense to prefix them.  I can fix up `pagination` and `progress` and submit a PR.

**Comment by IdanCo** [comment]
Cool!

And if you're in the mood, your PRs are always welcomed...

**Comment by lirantal** [comment]
Just jumping in quickly. If you're adding custom attributes and you don't want to mess up existing attributes or conflict with framework-specific stuff maybe you can use `data-` attributes which are the sanctuary for custom attributes in HTML5 (see [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*))
